
services:
  infotafel-frontend:
    build:
      context: ./infotafel
      dockerfile: Dockerfile
      network: host
    container_name: infotafel_next_frontend#
    environment:
      - NEXT_PUBLIC_BACKEND_APP_API_URL
      - NEXT_PUBLIC_STRAPI_APP_API_URL
    ports:
      - "9990:3000"
      - "9991:8000" # Map host port 9991 to container port 9991
    restart: always
  infotafel_cms:
    build:
      context: ./infotafel-cms
      dockerfile: Dockerfile
      network: host
    container_name: infotafel_cms
    ports:
      - "9993:1337"
    restart: always
    
