

services:
  infotafel-frontend:
    build:
      context: ./infotafel
      dockerfile: Dockerfile
      network: host
    container_name: infotafel_next_frontend
    ports:
      - "9990:3000"
      - "9991:8000" # Map host port 9991 to container port 9991
    restart: always

