version: "3.8"

services:
  infotafel-frontend:
    build:
      context: ./infotafel
      dockerfile: Dockerfile
      network: host
    container_name: infotafel_next_frontend
    working_dir: /usr/src/app
    ports:
      - "9991:3000"
    volumes:
      - infotafel_frontend_data:/usr/src/app
    networks:
      - infotafel_default
    command: ["sh", "-c", "npm install && npm run start"]  # Added npm install
    restart: always

  infotafel-backend:
    build:
      context: ./infotafel
      dockerfile: Dockerfile
      network: host
    container_name: infotafel_next_backend
    working_dir: /usr/src/app
    ports:
      - "9992:8000"
    volumes:
      - infotafel_backend_data:/usr/src/app
    networks:
      - infotafel_default
    command: ["sh", "-c", "npm install && npm run start-node"]  # Added npm install
    restart: always

  infotafel-cms:
    build:
      context: ./infotafel-cms
      dockerfile: Dockerfile
      network: host
    container_name: infotafel_cms
    working_dir: /usr/src/cms
    ports:
      - "9993:1337"
    volumes:
      - infotafel_cms_data:/usr/src/cms
    networks:
      - infotafel_default
    command: ["sh", "-c", "npm install && npm run start-strapi"]  # Added npm install
    restart: always

volumes:
  infotafel_frontend_data:
  infotafel_backend_data:
  infotafel_cms_data:

networks:
  infotafel_default:
    driver: bridge
