version: "3.8"

services:
  infotafel-frontend:
    build: ./infotafel
    container_name: infotafel_next_frontend
    working_dir: /usr/src/app
    ports:
      - "9991:3000"  # Use port 9991 on the host for Next.js frontend
    networks:
      - infotafel_default
    volumes:
      - ./infotafel:/usr/src/app
    command: ["npm", "run", "start"] # Startbefehl für das Frontend
    restart: always

  infotafel-backend:
    build: ./infotafel
    container_name: infotafel_next_backend
    working_dir: /usr/src/app
    ports:
      - "9992:8000"  # Use port 9992 on the host for Node.js backend
    networks:
      - infotafel_default
    volumes:
      - ./infotafel:/usr/src/app
    command: ["npm", "run", "start-node"] # Startbefehl für das Backend
    restart: always

  infotafel-cms:
    build: ./infotafel-cms
    container_name: infotafel_cms
    networks:
      - infotafel_default
    working_dir: /usr/src/cms
    ports:
      - "9993:1337"  # Use port 9993 on the host for Strapi CMS
    volumes:
      - ./infotafel-cms:/usr/src/cms
    command: ["npm", "run", "start-strapi"]
    restart: always


networks:
  # The presence of these objects is sufficient to define them
  infotafel_default: {}