version: "3.8"

services:
  infotafel-frontend:
    build: ./infotafel
    container_name: infotafel_next_frontend
    working_dir: /usr/src/app
    ports:
      - "9991:3000"
    networks:
      - infotafel_default
    volumes:
      - ./infotafel:/usr/src/app
    command: ["npm", "run", "start"]
    restart: always

  infotafel-backend:
    build: ./infotafel
    container_name: infotafel_next_backend
    working_dir: /usr/src/app
    ports:
      - "9992:8000"
    networks:
      - infotafel_default
    volumes:
      - ./infotafel:/usr/src/app
    command: ["npm", "run", "start-node"]
    restart: always

  infotafel-cms:
    build: ./infotafel-cms
    container_name: infotafel_cms
    working_dir: /usr/src/cms
    ports:
      - "9993:1337"
    networks:
      - infotafel_default
    volumes:
      - ./infotafel-cms:/usr/src/cms
    command: ["npm", "run", "start-strapi"]
    restart: always

networks:
  infotafel_default:
    external: true
