version: "3.8"

services:
  infotafel-frontend:
    build: 
      context: ./infotafel
      dockerfile: Dockerfile
      network: host
    container_name: infotafel_next_frontend
    working_dir: /usr/src/app  # This should be where the package.json of the frontend is
    ports:
      - "9991:3000"
    volumes:
      - infotafel_frontend_data:/usr/src/app  # Named volume
      - infotafel_frotnend_data/node_modules
    command: ["npm", "run", "start"]
    restart: always

  infotafel-backend:
    build: 
      context: ./infotafel
      dockerfile: Dockerfile
      network: host
    container_name: infotafel_next_backend
    working_dir: /usr/src/app  # This should be where the package.json of the backend is
    ports:
      - "9992:8000"
    volumes:
      - infotafel_backend_data:/usr/src/app  # Named volume
      - infotafel_backend_data/node_modules
    command: ["npm", "run", "start-node"]
    restart: always

  infotafel-cms:
    build: 
      context: ./infotafel-cms
      dockerfile: Dockerfile
      network: host
    container_name: infotafel_cms
    working_dir: /usr/src/cms  # This should be where the package.json of the CMS is
    ports:
      - "9993:1337"
    volumes:
      - infotafel_cms_data:/usr/src/cms  # Named volume
      - infotafel_cms_data/node_modules
    command: ["npm", "run", "start-strapi"]
    restart: always

volumes:
  infotafel_frontend_data:
  infotafel_backend_data:
  infotafel_cms_data:

networks:
  infotafel_default:
    driver: bridge
