version: "3.8"

services:
  infotafel-frontend:
    build: 
      context: ./infotafel
      dockerfile: Dockerfile
      network: stack
    container_name: infotafel_next_frontend
    working_dir: /usr/src/app  # This should be where the package.json of the frontend is
    ports:
      - "9991:3000"
      - "9992:8000"
    volumes:
      - infotafel_frontend_data:/usr/src/app  # Named volume
    networks:
      - infotafel_default
    command: ["sh", "-c", "npm run build && npm run start"]  # Run build before start
    restart: always

  infotafel-cms:
    build: 
      context: ./infotafel-cms
      dockerfile: Dockerfile
      network: stack
    container_name: infotafel_cms
    working_dir: /usr/src/cms  # This should be where the package.json of the CMS is
    ports:
      - "9993:1337"
    volumes:
      - infotafel_cms_data:/usr/src/cms  # Named volume
    networks:
      - infotafel_default
    command: ["npm", "run", "start"]
    restart: always

volumes:
  infotafel_frontend_data:
  infotafel_cms_data:

networks:
  infotafel_default:
    driver: bridge
