
services:
  infotafel-frontend:
    build:
      context: ./infotafel
      dockerfile: Dockerfile
      network: host
    ports:
      - "9990:3000"
      - "9991:8000" # Map host port 9991 to container port 9991
    restart: always
    env_file:
      - stack.env 
  infotafel_cms:
    build:
      context: ./infotafel-cms
      dockerfile: Dockerfile
      network: host
    container_name: infotafel_cms
    ports:
      - "9993:1337"
    restart: always
    
networks:
  infotafel-2024: 
    driver: bridge